version: '3.4'

services:
  rails:
    image: cryptopus-dev/rails
    user: "${UID:-1000}"
    tty: true
    stdin_open: true
    environment:
      RAILS_DB_ADAPTER: 'postgresql'
      RAILS_DB_HOST: 'postgres'
      RAILS_DB_PORT: 5432
      RAILS_DB_USERNAME: postgres
      RAILS_DB_PASSWORD: password
      DISPLAY: ${DISPLAY}

    build:
      context: ../development
      dockerfile: Rails.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ../../../:/myapp
      - ../../../tmp/seed:/seed
      - ../development/rails/bin/prepare-frontend.sh:/myapp/bin/prepare-frontend.sh:ro
      - ./database.yml:/myapp/config/database.yml:ro
      - ../development/home/rails:/home/developer
      - bundler_cache:/opt/bundle
      - /tmp/.X11-unix:/tmp/.X11-unix
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgres
  ember:
    image: cryptopus-dev/ember
    tty: true
    user: "${UID:-1000}"
    stdin_open: true
    build:
      context: ../development
      dockerfile: Ember.dockerfile
    volumes:
      - ../../../frontend:/myapp
      - ../../../tmp/bash_history:/root/.bash_history
      - yarn_cache:/myapp/node_modules
    tmpfs:
      - /myapp/tmp
    ports:
      - "4200:4200"
      - "7020:7020"
      - "7357:7357"
volumes:
  bundler_cache:
  yarn_cache:
  postgres:
