# frozen_string_literal: true

source 'http://rubygems.org'

gem 'rails', '~> 6.1.3'

gem 'figaro'
gem 'mysql2'
gem 'net-ldap'
gem 'puma'
gem 'sqlite3'

gem 'active_model_serializers'
gem 'annotate'
gem 'bleib', '0.0.9'
gem 'bootstrap-select-rails'
gem 'breadcrumbs_on_rails'
gem 'clipboard'
gem 'coffee-rails'
gem 'countries', require: 'countries/global'
gem 'dynamic_form'
gem 'faker'
gem 'haml'
gem 'handlebars_assets'
gem 'i18n-js', '~> 3.0'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'jquery-ui-rails'
gem 'less-rails'
gem 'maxmind-db'
gem 'openid_connect'
gem 'password_strength'
gem 'pundit'
gem 'rails-i18n'
gem 'sass-rails'
gem 'seed-fu'
gem 'selectize-rails'
gem 'sentry-raven'
gem 'sprockets', '~>3'
gem 'therubyracer'
gem 'turbolinks'
gem 'twitter-bootstrap-rails', '~>3.2'
gem 'uglifier'
gem 'webpacker'

group :development, :test do
  gem 'bullet'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'fabrication'
  gem 'launchy'
  gem 'mocha'
  gem 'rails-controller-testing'
  gem 'rails-erd'
  gem 'rspec-rails', '~> 4.0'
  gem 'rubocop', '~> 0.79.0'
  gem 'rubocop-checkstyle_formatter', '~> 0.4.0'
  gem 'rubocop-rails', '~> 2.4.2'
  gem 'selenium-webdriver'
  gem 'simplecov', require: false, group: :test
  gem 'webdrivers'
  gem 'webmock'
end

group :development do
  gem 'brakeman', require: false
  gem 'hirb'
  gem 'pry'
  gem 'pry-stack_explorer'
  gem 'sextant'
end
