#!/bin/bash

set -ex

pushd /opt/app-root/src
echo $OPENSHIFT_BUILD_COMMIT > BUILD_INFO

yarn --cwd frontend/ install
yarn --cwd frontend/ build-prod
mkdir /opt/app-root/src/public/ember
mv -v frontend/dist/* /opt/app-root/src/public/ember/

# Replace ember source
sed -i 's/http:\/\/localhost:4200/\/ember/g' /opt/app-root/src/app/views/layouts/application.html.haml
vendorjs="$(grep -oP '(?<=<script src="\/assets\/)vendor-[a-z|\d]{32}.js' /opt/app-root/src/public/ember/index.html)"
vendorcss="$(grep -oP '(?<=<link integrity="" rel="stylesheet" href="\/assets\/)vendor-[a-z|\d]{32}.css' /opt/app-root/src/public/ember/index.html)"
frontendjs="$(grep -oP '(?<=<script src="\/assets\/)frontend-[a-z|\d]{32}.js' /opt/app-root/src/public/ember/index.html)"
frontendcss="$(grep -oP '(?<=<link integrity="" rel="stylesheet" href="\/assets\/)frontend-[a-z|\d]{32}.css' /opt/app-root/src/public/ember/index.html)"
sed -i "s/vendor.js/$vendorjs/g" /opt/app-root/src/app/views/layouts/application.html.haml
sed -i "s/vendor.css/$vendorcss/g" /opt/app-root/src/app/views/layouts/application.html.haml
sed -i "s/frontend.js/$frontendjs/g" /opt/app-root/src/app/views/layouts/application.html.haml
sed -i "s/frontend.css/$frontendcss/g" /opt/app-root/src/app/views/layouts/application.html.haml
popd
