# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "accounts", :force => true do |t|
    t.column "accountname", :string,    :limit => 40, :default => "", :null => false
    t.column "group_id",    :integer,                 :default => 0,  :null => false
    t.column "description", :text
    t.column "username",    :binary
    t.column "password",    :binary
    t.column "created_on",  :timestamp,                               :null => false
    t.column "updated_on",  :timestamp,                               :null => false
  end

  create_table "groups", :force => true do |t|
    t.column "name",        :string,   :limit => 40, :default => "", :null => false
    t.column "description", :text
    t.column "created_on",  :datetime,                               :null => false
    t.column "updated_on",  :datetime,                               :null => false
    t.column "team_id",     :integer,                :default => 0,  :null => false
  end

  create_table "items", :force => true do |t|
    t.column "account_id",   :integer,   :default => 0, :null => false
    t.column "description",  :text
    t.column "file",         :binary
    t.column "created_on",   :timestamp,                :null => false
    t.column "updated_on",   :timestamp,                :null => false
    t.column "filename",     :text,                     :null => false
    t.column "content_type", :text,                     :null => false
  end

  create_table "ldapsettings", :force => true do |t|
    t.column "basename",   :string, :limit => 200, :default => "ou=users,dc=yourdomain,dc=com", :null => false
    t.column "hostname",   :string, :limit => 50,  :default => "yourdomain.com",                :null => false
    t.column "portnumber", :string, :limit => 10,  :default => "636",                           :null => false
    t.column "encryption", :string, :limit => 30,  :default => "simple_tls",                    :null => false
  end

  create_table "recryptrequests", :force => true do |t|
    t.column "user_id", :integer, :default => 0, :null => false
  end

  create_table "teammembers", :force => true do |t|
    t.column "team_id",    :integer
    t.column "password",   :binary,                       :null => false
    t.column "user_id",    :integer,   :default => 0,     :null => false
    t.column "created_on", :timestamp,                    :null => false
    t.column "updated_on", :timestamp,                    :null => false
    t.column "team_admin", :boolean,   :default => false, :null => false
  end

  create_table "teams", :force => true do |t|
    t.column "name",        :string,    :limit => 40
    t.column "description", :text
    t.column "created_on",  :timestamp,                                  :null => false
    t.column "updated_on",  :timestamp,                                  :null => false
    t.column "visible",     :boolean,                 :default => true,  :null => false
    t.column "private",     :boolean,                 :default => false, :null => false
    t.column "noroot",      :boolean,                 :default => false, :null => false
  end

  create_table "users", :force => true do |t|
    t.column "public_key",  :text,                       :null => false
    t.column "private_key", :binary,                     :null => false
    t.column "password",    :binary
    t.column "admin",       :boolean, :default => false, :null => false
    t.column "uid",         :integer,                    :null => false
  end

end
